version: '2.3'
services:
  plugin:
    image: registry.gitlab.com/vaisawesome/randd/nlp/spelling-oov:0.1
    build: .
    ports:
      - "5000:5000"
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

